# Site settings
title: "Javier Gallardo - Data Analyst"
email: "javierivan.gallardo@gmail.com"
description: >-
  Bienvenido a mi sitio web. Aquí encontrarás mis proyectos de ciencia de datos, experiencia profesional y más sobre mi actividades.
twitter_username: jigsowl
github_username: jigsowl
minimal_mistakes_skin: "dark"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "America/Santiago"

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author information
author:
  name: "Javier Gallardo S"
  avatar: "/assets/images/profile.jpg" # Coloca aquí la ruta de tu foto
  bio: "Ingeniero Comercial, Científico de Datos en formación, y creador de contenido. Explorando el mundo de la ciencia y el streaming."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jigsowl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/javiergallardos"
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/jigsowl"

# Footer links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jigsowl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/javiergallardos"
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/jigsowl"

# Defaults for posts and pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
